name: "Windows: Test"

on: [push]

jobs:
  run-linters:
    name: Run linters
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          # - { sys: mingw64, env: x86_64, C: gcc, CXX: g++ }
          - { sys: clang64, env: clang-x86_64, C: clang, CXX: clang++ }

    steps:
      - name: Check out Git repo
        uses: actions/checkout@v3

      - name: Install CMake
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          install: 
            mingw-w64-${{matrix.env}}-openssl
            mingw-w64-${{matrix.env}}-toolchain  
            mingw-w64-${{matrix.env}}-cmake

      - name: Build cmake
        shell: msys2 {0}
        run: |
          echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
          echo $(pacman -S ${{matrix.C}})
          echo $(pacman -S ${{matrix.CXX}})
          cd Team11/Code11
          mkdir build
          cd build
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_C_COMPILER=${{matrix.C}} -DCMAKE_CXX_COMPILER=${{matrix.CXX}}
          cmake --build . --config Debug

      - name: Run Unit Tests
        run: |
          cd Team11/Code11/build/src/unit_testing
          ./unit_testing

      - name: Run Integration Tests
        run: |
          cd Team11/Code11/build/src/integration_testing
          ./integration_testing
