@startuml qps_parser


abstract class DeclarationParser
abstract class ClauseParser
abstract class SynonymParser

class QpsParser {
    - ClauseParser clauseParser
    - SynonymParser synonymParser
    - DeclarationParser declarationParser
    +parse()
}


QpsParser --> QpsClauseParser

QpsClauseParser --> SuchThatParser
QpsClauseParser --> PatternParser

ClauseParser <|-- QpsClauseParser
ClauseParser <|.. SuchThatParser
ClauseParser <|.. PatternParser

@enduml
