@startuml qps_architecture
!define RECTANGLE component

RECTANGLE QueryProcessorSystem {
    
}

RECTANGLE QueryProcessorSystemTokenizer {

}

RECTANGLE QueryProcessorSystemParser {

}

RECTANGLE QueryProcessorSystemEvaluator {

}

QueryProcessorSystem --> QueryProcessorSystemParser: Parse Query
QueryProcessorSystemParser --> QueryProcessorSystemTokenizer: Tokenize Query
QueryProcessorSystem --> QueryProcessorSystemEvaluator: Evaluate Query
@enduml
