name: Doxygen Documentation
on: [pull_request]

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: "Team11/Code11/src/spa/docs"
          doxyfile-path: "Doxyfile.in"
          enable-latex: true
