name: "Windows: Lint cpp/h files and test"

on: [ push ]

jobs:
  run-testing:
    name: Run Testing
    runs-on: windows-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v3

      # ccache doesn't work well in windows
      - uses: lukka/get-cmake@latest
      - name: Build with cmake
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/Team11/Code11/CMakeLists.txt'
          cmakeAppendedArgs: '-DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_BUILD_TYPE=Debug'
          buildWithCMake: true
          buildDirectory: '${{ github.workspace }}/Team11/Code11/build'

      - name: Run linters
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          version: 16
          repo-root: "Team11/Code11"
          database: "build/compile_commands.json"
          ignore: "build | lib | cmake | src/autotester_gui | src/unit_testing | src/integration_testing"
          files-changed-only: false
          tidy-checks: "-*"
          step-summary: true

      - name: Check linter status
        if: steps.linter.outputs.clang-format-checks-failed > 0
        shell: bash
        run: echo "Some files failed the linting checks!" && exit 1

      # The unit test and integration test are often stuck, and none of the team members use MSVC so its hard to debug
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Run System Testing
        shell: bash
        run: |
          chmod +x $GITHUB_WORKSPACE/.github/scripts/run_sys_test.sh
          cd $GITHUB_WORKSPACE
          ./.github/scripts/run_sys_test.sh
