name: "MacOS: Test"

on: [ push ]

jobs:
  run-testing:
    name: Run Testing
    runs-on: macos-latest
    strategy:
      fail-fast: true

    steps:
      - name: Check out Git repo
        uses: actions/checkout@v3

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.11
        with:
          create-symlink: true

      - uses: lukka/get-cmake@latest
      - name: Setup Clang
        run: brew install llvm

      - name: Build with cmake
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/Team11/Code11/CMakeLists.txt'
          cmakeAppendedArgs: '-DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang  -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache'
          buildWithCMake: true
          buildDirectory: '${{ github.workspace }}/Team11/Code11/build'

      - name: Run linters
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          version: 16
          repo-root: "Team11/Code11"
          database: "build/compile_commands.json"
          ignore: "build | lib | cmake | src/autotester_gui | src/unit_testing | src/integration_testing"
          files-changed-only: false
          tidy-checks: "-*"
          step-summary: true

      - name: Check linter status
        if: steps.linter.outputs.clang-format-checks-failed > 0
        run: echo "Some files failed the linting checks!" && exit 1

      - name: Run Unit Tests
        run: |
          cd Team11/Code11/build/src/unit_testing
          ./unit_testing

      - name: Run Integration Tests
        run: |
          cd Team11/Code11/build/src/integration_testing
          ./integration_testing