name: Lint cpp/h files

on: [ push ]

jobs:
  run-linters:
    name: run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repo
        uses: actions/checkout@v3

      - name: Setup CMake
        run: sudo apt install -y cmake

      - name: Build cmake
        run: |
          cd Team11/Code11
          mkdir build
          cd build
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=1
          make -j4 

      - name: Upload integration test
        uses: actions/upload-artifact@v4
        with:
          name: integration_testing
          path: Team11/Code11/build/src/integration_testing/integration_testing

      - name: Upload unit test
        uses: actions/upload-artifact@v4
        with:
          name: unit_testing
          path: Team11/Code11/build/src/unit_testing/unit_testing

      - name: Run linters
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          version: 16
          repo-root: 'Team11/Code11'
          database: 'build/compile_commands.json'
          ignore: 'build | lib | cmake | src/autotester_gui'
          step-summary: true

      - name: Check linter status
        if: steps.linter.outputs.clang-format-checks-failed > 0
        run: echo "Some files failed the linting checks!" && exit 1

  run-unit-testing:
    name: Run Unit Testing
    runs-on: ubuntu-latest
    needs: run-linters

    steps:
      - name: Download unit testing from linters
        uses: actions/download-artifact@v4
        with:
          name: unit_testing

      - name: Run Unit Test
        run: |
          chmod +x unit_testing
          ./unit_testing

  run-integration-testing:
    name: Run Integration Testing
    runs-on: ubuntu-latest
    needs: run-linters

    steps:
      - name: Download integration testing from linters
        uses: actions/download-artifact@v4
        with:
          name: integration_testing

      - name: Run Integration Test
        run: |
          chmod +x integration_testing
          ./integration_testing
