name: "MacOS: Test"

on: [push]

jobs:
  run-linters:
    name: run linters
    runs-on: macos-latest

    steps:
      - name: Check out Git repo
        uses: actions/checkout@v3

      - name: Build cmake
        run: |
          cd Team11/Code11
          mkdir build
          cd build
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_BUILD_TYPE=Debug
          make -j4

      - name: Run Unit Tests
        run: |
          cd Team11/Code11/build/src/unit_testing
          ./unit_testing

      - name: Run Integration Tests
        run: |
          cd Team11/Code11/build/src/integration_testing
          ./integration_testing
