name: "MacOS: Test"

on: [ push ]

jobs:
  run-testing:
    name: Run Testing
    runs-on: macos-latest

    steps:
      - name: Check out Git repo
        uses: actions/checkout@v3

      - name: Build cmake
        run: |
          cd Team11/Code11
          mkdir build
          cd build
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_BUILD_TYPE=Debug
          make -j4

      - name: Run Unit Tests
        run: |
          cd Team11/Code11/build/src/unit_testing
          ./unit_testing

      - name: Run Integration Tests
        run: |
          cd Team11/Code11/build/src/integration_testing
          ./integration_testing

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run System Testing on Push
        run: |
          python3 Team11/run_autotester.py Team11/Tests11/simple_source.txt Team11/Tests11/simple_queries.txt -i
